### ISSUE TITLE
Should we raise an issue with React for pluggable createElement?

### ISSUE THREAD

**Issue by gaearon** [rackt/react-a11y#1]
Monkeypatching doesn't feel quite nice..

Should we file an issue with React to provide injectable “dev-linting” in `createElement`?
Would this beneficial to any other projects?

Or is it too localized problem?

**Comment by rpflorence** [comment]
For now I'm fine duck punching `createElement`, it was @spicy's suggestion after I found `ReactCompositeComponent.injections.injectMixin` didn't work for native elements. Folks shouldn't be doing it in production anyway.

If this lib gains traction and others can think of a reason to do similar things then I think we should start asking for it.
