### ISSUE TITLE
Bower Support

### ISSUE THREAD

**Issue by evnaverniouk** [rackt/react-a11y#12]
Can you please add bower support to this package? We'd like to use react-a11y on the client-side, and bower makes this much easier for us.

**Comment by AsaAyers** [comment]
I recommend a PR that adds bower support. I know for projects I maintain (not this one) I'm MUCH more likely to add support for something I don't use if someone will provide a PR that does all the work. IIRC bower just requires one json file.

I quit using bower and just moved to using npm for my client side code months ago.

**Comment by kloots** [comment]
Closing after chatting with @angus-c: per @AsaAyers comment, most people have moved to npm for client side code so no plans for Bower support.
