### ISSUE TITLE
Rails + Browserify issues

### ISSUE THREAD

**Issue by rpearce** [rackt/react-a11y#13]
Thank you so much for making this! I've successfully used `react-a11y` on a Node project, but I am trying to implement this in my day job at [Articulate](https://www.articulate.com/).

Stack in addition to React:
* Rails
* NPM
* browserify-rails

I know the code is being loaded on the page, but I can't seem to trigger any warnings/errors no matter how bad my code is (for example, rendering anchor tags with `'#'` as the `href` with no `role` or anthing).

Any help would be much appreciated,
Robert

**Comment by kloots** [comment]
Is this still an issue for you? If so, can you expand on the problem you are experiencing? What debugging tactics have you tried?

**Comment by kloots** [comment]
Closing as I've not heard back from @rpearce.

**Comment by rpearce** [comment]
Sorry about that. It is no longer an issue.  



—
Robert Pearce

http://www.robertwpearce.com

https://www.linkedin.com/in/robertwpearce



m-US: 1.843.568.9080

m-UK: +44 7477 424374
