### ISSUE TITLE
React 0.13 support (conflicting peerDependency)

### ISSUE THREAD

**Issue by RickWong** [rackt/react-a11y#16]
Don't know what to fix without react-a11y telling me. :disappointed:

**Comment by AsaAyers** [comment]
> until we have a replacement for current mixin use cases and support for class property initializers in the language, we don't plan to deprecate React.createClass.

You know you don't have to stop using `React.createClass`. Mixins are far more powerful than inheritance, so I'm sticking with `React.createClass` until they solve mixins for ES6 classes.

**Comment by RickWong** [comment]
@AsaAyers Yes I know. The problem is the dependency and peerDependency on React 0.12.

**Comment by nickcolley** [comment]
Yeah run into this too. :+1:

**Comment by songawee** [comment]
+1 to this issue. It's preventing us from upgrading to react-0.13.x. Would you accept a pull request that updates the package.json? Or do you foresee incompatibilities with React 0.13.x?

**Comment by pluma** [comment]
Had to remove react-a11y because of the peerDependency conflict. Would love to see this addressed, too.

**Comment by iam4x** [comment]
until #23 is merged:

* `npm install --save-dev iam4x/react-a11y#patch-1`

**Comment by yidea** [comment]
+1

**Comment by AsaAyers** [comment]
See #24. Instead of requiring react my branch has you pass in any version you want. It's available with several other fixes on npm as @asaayers/react-a11y

**Comment by necolas** [comment]
Same issue for us.

**Comment by bmcmahen** [comment]
Same for me -- love this tool, btw.

**Comment by AsaAyers** [comment]
@ryanflorence is react-a11y still being supported? There are 10 open PRs. 4 of them are mine and would close 4 other PRs and 1 issue including this one.

**Comment by mmrtnz** [comment]
+1 This is a great tool! I'll be using @iam4x's work around in the mean time.

**Comment by mathieumg** [comment]
+1 :+1:

**Comment by kloots** [comment]
Fixed by PR #28

**Comment by mmrtnz** [comment]
Can you please updated npm with this PR? The [package description](https://www.npmjs.com/package/react-a11y) still has the old documentation and continues to throw this error.

**Comment by AsaAyers** [comment]
That documentation is accurate for the version that is on npm. Once a new version is released that page will update automatically.

**Comment by mmrtnz** [comment]
Okay thanks for the info @AsaAyers!
