### ISSUE TITLE
hasChildTextNode cannot handle an undefined child. 

### ISSUE THREAD

**Issue by allanhortle** [rackt/react-a11y#20]
If the `children` array has an undefined child it will throw undefined errors for `child.type`. It's probably due to bad render functions on the users end, but it is confusing none the less. An error message would be useful.

**Comment by kloots** [comment]
Is this still an issue? Wasn't this fixed in PR #7?

**Comment by kloots** [comment]
Closing as we've not heard back and I'm pretty sure this was covered in PR #7.
