### ISSUE TITLE
Thoughts on react-a11y and ESLint

### ISSUE THREAD

**Issue by evnaverniouk** [rackt/react-a11y#25]
I wonder if react-a11y might be better served as an ESLint plugin (similar to https://www.npmjs.com/package/eslint-plugin-react)?

Currently, to use react-a11y you need to load it into your code (remembering to remove it for production builds), run your app, open the dev tools, review the warnings, go back to your code editor, make the fix, then reload the app again to confirm the warning went away. With ESLint, those warnings could be directly integrated into build tools, and code editors without having to actually execute the application code.

Any thoughts?

**Comment by kloots** [comment]
Feels out of scope for this project. This isn't meant to be a static analysis tool.

**Comment by evcohen** [comment]
@globexdesigns https://github.com/evcohen/eslint-plugin-jsx-a11y working on that right now, let me know if you'd like to help!
