### ISSUE TITLE
Switch to headless tests

### ISSUE THREAD

**Issue by kloots** [rackt/react-a11y#38]
Suggestion from @AsaAyers, worth investigating:
I don’t think the tests actually require a browser. What do you think of switching to headless tests? I have a couple projects using Jest and I really like it. I’m not sure if the tests even need a DOM, so plain jasmine-node may be an even be an option.

**Comment by ryanflorence** [comment]
seems fine until we have assertions around focus management, and maybe even simulating events, but we don't have any yet.

**Comment by AsaAyers** [comment]
See #32 it's done

**Comment by kloots** [comment]
@AsaAyers I'm hesitant to merge your PR based on @ryanflorence's comment. Those sorts of tests would be a good addition.

**Comment by ryanflorence** [comment]
easy to switch back :)

**Comment by ryanflorence** [comment]
closed by #32
