### ISSUE TITLE
Potential es5 goodies causing js errors in Android browser and IE8

### ISSUE THREAD

**Issue by dougmcclurg** [rackt/react-a11y#8]
Amazing project, love the work you are doing!

Just noticed if i require react-a11y before my es5 shims and shams i get JS errors on IE8 and older Android browsers.
Unfortunately neither of these devices/technologies allow me to get a valid error message that i can pass on to you guys. My minimal investigation tells me IE8 and android(internet) is not handling some es5 or 6 goodies. 

Requiring the library after the es5 shim works fine.

**Comment by necolas** [comment]
This isn't a bug, since React requires an es5 shim too: https://facebook.github.io/react/docs/working-with-the-browser.html#browser-support-and-polyfills
